spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: cucustomerslist
          uri: http://localhost:8282
          predicates:
            - Path=/customerslist/**
        - id: customerdetail
          uri: http://localhost:8282
          predicates:
            - Path=/customerdetail/**
        - id: product
          uri: http://localhost:8383
          predicates:
            - Path=/product/**
        - id: productlist
          uri: http://localhost:8383
          predicates:
            - Path=/productlist/**
        - id: manageproduct
          uri: http://localhost:8383
          predicates:
            - Path=/manageproduct/**
            
  security:
    oauth2:
      client:
        provider:
          keycloak-server:
            issuer-uri: http://localhost:8080/auth/realms/SecureMicroservices
        registration:
          keycloak-spring-gateway-client:
               provider: keycloak-server
               client-id: spring-boot-application
               client-secret: 7235c270-135b-4c40-b18b-3a8dbddd13f4
               authorization-grant-type: authorization_code
               redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"                    
server:
  port: 80